### ISSUE TITLE
スポンサー情報更新

### ISSUE THREAD

**Issue by ukkari** [mitou/jr.mitou.org#10]

**Comment by yasulab** [comment]
スポンサー情報はコチラから修正できます！(権限があればブラウザからでも編集できるはず)
https://github.com/mitou/jr.mitou.org/blob/master/_data/sponsors.yml

![image](https://user-images.githubusercontent.com/155807/73509856-eed98b80-4423-11ea-8ae4-69c9b1a954c6.png)
