### ISSUE TITLE
トップページPMエリアが静止画

### ISSUE THREAD

**Issue by ukkari** [mitou/jr.mitou.org#11]

**Comment by yuki384** [comment]
対応しますー

**Comment by yuki384** [comment]
対応しました！ymlから読んでます！
https://github.com/mitou/jr.mitou.org/commit/64150d03d643e41f667f63d3751f4aff8fa5d935

![image](https://user-images.githubusercontent.com/31533303/73451460-04f73580-43ab-11ea-9416-1f0ee7dda03a.png)
![image](https://user-images.githubusercontent.com/31533303/73451482-0fb1ca80-43ab-11ea-9adb-10a5e542c71d.png)

**Comment by yasulab** [comment]
キャー！対応ありがとうございます...!! (＞人＜ )💖✨
