### ISSUE TITLE
スマホで横スクロールしてしまう

### ISSUE THREAD

**Issue by ukkari** [mitou/jr.mitou.org#14]
実際にはスクロールできないんですけど、bounceエフェクトがかかってしまいます。（開いて見れば言っている意味がわかります）
https://www.1-firststep.com/archives/7059

**Comment by ukkari** [comment]
トップページのみですねこれおきるの

**Comment by ukkari** [comment]
Developer Toolとかではおきない（なぜｗ）

**Comment by yuki384** [comment]
多分治った…はずです＞＜
見出しの横の線が変な動きをしていたっぽいです。
https://github.com/mitou/jr.mitou.org/commit/d26c04d7c46aa9af3df68ff07a60f60b562021e7

**Comment by ukkari** [comment]
解決確認しました！
