### ISSUE TITLE
海外からも参照できるように、英語のプロジェクト紹介ページを作る

### ISSUE THREAD

**Issue by yasulab** [mitou/jr.mitou.org#19]
> @ukkari: 英語圏ページは海外の大学などに進学する人の実績がわかればいいので、別に全部翻訳する必要ないんですよね、よく考えると。
> 
> @yasulab: 確かに。翻訳ではなくメンテしなくても長く使える構成にしておくと良さそうかな思いました d(￣ ￣)✨
> 
> @ukkari: そうしましょう
> 
> @yasulab: ひとまずは既存の英語ページを使い回して、日本語のデザインが整ったらそれをベースに英語ページを更新する感じで行くと良さそうですね。翻訳ではないため、英語ページはコンテンツ作成や情報整理も関わってくるので、僕や鵜飼さんで対応すると良さそうです 🔧💨✨
> 
> @ukkari: そうしましょう

cf. https://mattermost.jr.mitou.org/mitoujr/pl/yd7rcdtrnfgs9qkzz17h3wx7bw

## 進め方

- [ ] 既存のデザインを再利用して、英語ページを作る
- [ ] 既存の英文を再利用 + 新規の英文の草案を作る
- [ ] 英文チェック + 追記・添削など

**Comment by ukkari** [comment]
これ、僕の方で既存の英文を再利用＋新デザインで作りましょうか？

**Comment by yasulab** [comment]
@ukkari おー！お願いできると嬉しいです！(＞人＜ )✨

#20 のスパクリ対応も対応したいので、では僕の方でこっちやります！🛠💨✨

**Comment by yasulab** [comment]
> * 既存のデザインを再利用して、英語ページを作る

ここだけちょっと作っちゃいますね 🛠💨✨

**Comment by yasulab** [comment]
あ、どうだろう。ちょっと Mattermost で相談します！

**Comment by yasulab** [comment]
こちら鵜飼さんにお願いすることにしました！僕は #20 対応します 🛠💨✨
