### ISSUE TITLE
過去プロジェクトの年度が押せるか不明

### ISSUE THREAD

**Issue by ukkari** [mitou/jr.mitou.org#5]
過去のプロジェクトのところ、年度の部分が押せるというのはわからなすぎるので、デザインでなんとかしてほしい所存

**Comment by yuki384** [comment]
プロジェクトページを分けることで解決しました！
(デザインを変えても良いですが、読み込み時間がかかってしまうので分けることにしました ;) )

https://github.com/mitou/jr.mitou.org/commit/d3ddc19b8cb1b523b919e24980b6d203cfb5613d
