### ISSUE TITLE
未踏社団ロゴでかすぎ

### ISSUE THREAD

**Issue by ukkari** [mitou/jr.mitou.org#9]

**Comment by yuki384** [comment]
対応しました！
https://github.com/mitou/jr.mitou.org/commit/e2052da94881da40e7c66c63e8049105134955b5
PC
![image](https://user-images.githubusercontent.com/31533303/73449321-3d484500-43a6-11ea-9aac-962d35930acf.png)
スマホ
![image](https://user-images.githubusercontent.com/31533303/73449348-49cc9d80-43a6-11ea-816c-305eeb06227c.png)
